import Head from 'next/head'
import ContactForm from '../components/forms/ContactForm'
import Hero from '../components/common/Hero'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>HFTF - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height="h-96 -mt-16" />
      <div className='flex flex-wrap w-full justify-center bg-gray-50'>
        <div className='flex flex-wrap w-11/12 md:w-10/12 py-10'>
          <div className='w-full md:w-1/2'>
            <ContactForm />
          </div>
          <div className='w-full text-gray-600 md:w-1/2 md:pl-10 mt-10 md:mt-0'>
            <div className='text-xl font-semibold'>
              Address
            </div>
            <div className='w-full bg-gray-200 h-56 mt-5'>

            </div>
            <div className='ml-3 capitalize'>
              <br></br>HEIDEVELD CENTER (1st Floor)
              <br></br>40 ASCENSION ROAD
              <br></br>HEIDEVELD
              <br></br>CAPE TOWN
              <br></br>7764
            </div>
            <div className='text-xl font-semibold mt-4'>
              Contact
            </div>
            <div className='mt-3 ml-3'>
            021 023 7690 <br></br>076 073 6777 <br></br> 06 928 64263
            </div>
            </div>
          </div>
        </div>
        <div className='w-full bg-gray-50 h-[45vh]'>
{/* <Google /> */}
        </div>
    </div>
  )
}