import Head from 'next/head'
import Hero from '../components/common/Hero'

export default function Gallery() {
  return (
    <div>
      <Head>
        <title>HFTF - Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height="h-96 -mt-16"/>

    </div>
  )
}