import Head from 'next/head'
import Hero from '../components/common/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HFTF - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero height="h-screen -mt-16"/>
    </div>
  )
}
